### PR TITLE
Compiles with arrow 0.15 (NewTable API change)

### LINKED ISSUE #47: Compilation error with arrow 0.15
See attached.
[make.txt](https://github.com/353solutions/carrow/files/4002583/make.txt)

### PR DESCRIPTION
**Pull request by tebeka**
Fixes #47

### CODE REVIEW

**Comment by tebeka** [comment]
Merged as part of PR #51
